### ISSUE TITLE
MWfreq from .DSC only 2 relevant digits?

### ISSUE THREAD

**Issue by DanielK2012** [JeschkeLab/Hyscorean#3]
The microwave frequency read out from the Bruker .dsc file seems to have only 2 relevant digits after the comma... Minor issue, but would be nice to have all available in the .dsc file.

**Comment by luisfabib** [comment]
Where does this variable appear with only two digits? In the report, the GUI,...?

**Comment by DanielK2012** [comment]
Of course, sorry!
Yes, it's in the report.

**Comment by luisfabib** [comment]
Could you share the DSC file? 
There is nothing in the code that might round the MWfreq variable to 2 digits. 

Also I have reports where the MWfreq is reported with 4 digits. The issue might be in the DSC file.
